version: '3.8'
services:
  postgres:
    image: postgres:10.5
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6543:5432'
    volumes:
      # store postgres data on local machine
      - ./volumes/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to insert data
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql