spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: none
    show-sql: true