spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: none
    show-sql: true
    # enable @Lob (large object)
    properties.hibernate.jdbc.lob.non_contextual_creation: true
